version: "3.9"
services:
  password:
    build: .
    image: pwn/password:0.1
    volumes:
      - ./service/public:/home/password:ro
      - ./service/xinetd:/etc/xinetd.d/password:ro
    ports:
      - "3000:9999"
