version: "3.9"

services:
  traefik:
    image: traefik:v2.6
    container_name: "traefik"
    hostname: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # The Web UI 
      # - "7000:8080"
    secrets:
      - cloudflare_api_email
      - cloudflare_api_key
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/cloudflare_api_email
      - CF_API_KEY_FILE=/run/secrets/cloudflare_api_key
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/traefik.yml:ro
    labels:
      - "traefik.enable=true"
      # DNS challenge
      - "traefik.http.routers.traefik.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.$DOMAIN"
      - "traefik.http.routers.traefik.tls.domains[0].sans=$DOMAIN"
      # HTTP redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirect-https.entrypoints=web"
      - "traefik.http.routers.redirect-https.middlewares=redirect-to-https"

secrets:
  cloudflare_api_email:
    file: "./secrets/cloudflare_api_email.secret"
  cloudflare_api_key:
    file: "./secrets/cloudflare_api_key.secret"

networks:
  default:
    name: $DEFAULT_NETWORK
    external: true
